### ISSUE TITLE
Cannot use mangled identifiers in a fennel.eval environment

### ISSUE THREAD

**Issue by Benaiah** [bakpakin/Fennel#116]
When evaluating fennel code at runtime, it's impossible to use identifiers that require mangling.

Test case:

```fennel
>> ((. (require "fennel") :eval) "testEnv" {:env {:testEnv "hello"}})
"hello"
>> ((. (require "fennel") :eval) "test-env" {:env {:test-env "hello"}})
 
```

The `test-env` identifier in the evaluated code is mangled, but the `:test-env` key in the `:env` table is not, so the lookup fails.

**Comment by technomancy** [comment]
I think I know the fix for this: when `compile` gets an `opts.env` passed to it, it needs to look thru it and add to its scope's `manglings` and `unmanglings` for every key which isn't a valid Lua identifier.

I can take a swing at this later but if someone else wants to give it a shot it shouldn't be too difficult to add.

**Comment by bakpakin** [comment]
I have made a pull request that tries to address this issue in slightly different way than suggested by @technomancy. This should also work on generic enviornment tables even with metatables set.
