### ISSUE TITLE
Error with global functions when compiling to Lua

### ISSUE THREAD

**Issue by gustavohmsilva** [bakpakin/Fennel#153]
I created the following code in fennel:
```
(global gMin 1)
(global gMax 100)

(global guess (fn []
        (// (+ gMin gMax) 2)
))
```
When running fennel with the option --compile to generate a Lua file, I receive an incorrect code:
```
gMin = 1
gMax = 100
local function _0_()
  return ((gMin + gMax) // 2)
end
guess = _0_
return nil
```
The correct compilation code should have been:
```
gMin = 1
gMax = 100
function guess()
  return ((gMin + gMax) // 2)
end
```

I think it is a bug, or is something I'm just not getting? I understand that at the end the global guess will receive the function, but this code becomes severely complicated to follow the bigger the codebase becomes.

**Comment by bakpakin** [comment]
This code is correct.  As you have said, the value of the global will be the function `_0_` - they are semantically equivalent. In Lua, there is actually no difference in the result (except some debug information).

This is just due to the way the compiler works, yes in this particular case, it could be prettier. Also, try to avoid globals, although I know in may cases they are needed. Instead, use

```clojure
(global gMin 1)
(global gMax 100)
(fn guess [] (// (+ gmin gmax) 2))
```

compiles to

```lua
gMin = 1
gMax = 100
local function guess()
  return ((gMin + gMax) // 2)
end
return guess
```

**Comment by technomancy** [comment]
Sounds like this is a misunderstanding rather than a bug then?

**Comment by gustavohmsilva** [comment]
Yes, it is. Mostly a question of the design of the transpiled Lua code. Not a bug.
