### ISSUE TITLE
Clarify third-party lib mentions in tutorial

### ISSUE THREAD

**Issue by ryanford-frontend** [bakpakin/Fennel#194]
In the tutorial a couple third-party libraries are mentioned (lume and a utf8.lua) as the way to do a few things. Could you clarify that these are *not* included in the fennel rock and are just suggested workarounds?

**Comment by jaawerth** [comment]
Hi! Definitely up for clarifying any confusing language in the tutorial, but could you give some feedback on the particular sections you think need clearing up?

I think I see what you mean for **utf8.lua**, as it says
> Strings are essentially immutable byte arrays. UTF-8 support is provided from a [3rd-party library](https://github.com/Stepets/utf8.lua). Strings are concatenated with ..:
>  `(.. "hello" " world")`

Which could easily be misconstrued as this being done automatically, which isn't the case since Fennel aims to be a very minimal layer over Lua. Definitely agree that should be cleaned up.

For **lume**, I see
> Lua's standard library is very small, and thus several functions you might expect to be included are only found in 3rd-party libraries. For instance, finding the index in a table given a value is done by lume.find in the Lume library.

> Lua's standard library is quite small, and so common functions like map, reduce, and filter are absent. It's recommended to pull in something like Lume or luafun for those.

That doesn't read as ambiguous to *me*, but I welcome your thoughts if you think it is - I could see being more explicit about minimizing overhead and minimalism as why fennel doesn't introduce any runtime functions out of the box.

Are there any bits I'm missing you had in mind? I just did a quick ctrl+f :clown_face:

**Comment by ryanford-frontend** [comment]
Possibly something like:
> Lua's standard library is very small, and thus several functions you might expect to be included ~~are only found in 3rd-party libraries. For instance, finding the index in a table given a value is done by lume.find in the Lume library.~~ *, such as finding the index in a table given it's value, are not.*

> Lua's standard library is quite small, and so common functions like map, reduce, and filter are absent. It's recommended to pull in ~~something~~ *a 3rd-party utility library* like Lume or luafun for those *, as they're not provided by Fennel*.

**Comment by technomancy** [comment]
Thanks for the suggestion. I merged the two sections since it seemed redundant to have both.
