### ISSUE TITLE
each` should respect use of `values` in iterator position

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#201]
In the rare case of working with raw iterators in lua (that is, when you aren't getting them from an existing function like `pairs`/`ipairs`), it's not uncommon/impossible to have something like this, which works as expected in Lua:

```lua
for k, v in step, param, state do -- one might manipulate these in some scenarios
  print(k, v) -- or do whatever
end
```

Since `each` doesn't have the `in` separator to make it explicit which part is the iterator, and it treats the last form passed to the special as the iterator, one might expect to be able to achieve the same with:

```clojure
(each [k v (values step param state)] (print k v))
```
but this currently compiles to the (incorrect)
```lua
for k, v in step do
  print(k, v)
end
```

The only way to achieve this right now is to add an arbitrary function boundary, like
```clojure
(each [k v (select 1 step param state)] (print k v))
```
but I don't think this should be necessary for something so fundamental.

**Comment by jaawerth** [comment]
Looks like this is more inherent to how `values` expands when nested in certain contexts. Here's another one I came across while poking it:

**Test case**
```clojure
(print (or false (values 1 2)))
```
**Expected**
```lua
print(false or 1, 2)
```
**Actual**
```lua
print((false or 1 or 2))
```

**Comment by jaawerth** [comment]
Hrm, this is actually ambiguous enough that it'll be difficult to solve without making a tradeoff one way or the other with consistency:

- Right now, `(or a b (values c d e f))` evaluates to `(a or b or c or d or f)` (with the parens), which on the surface makes sense.
- Similarly `(* 1 2 3 (values 4 5))`
- it would be great if the nil-punning I'm showing in the above comment was possible, as we could use it to avoid extra closures, but it's probably not worth sacrificing the current semantics.
- There really should be a way to make `each` work with manually supplied `step, param, state`.

Maybe an optional separator in `each` is a better solution?

**Comment by technomancy** [comment]
Yes, given that iterators can return any number of values, there's no way in `each` to determine when the binding symbols end and the iterator values begin without some kind of separator. Unfortunately we don't really have any existing notation to indicate this kind of separation.

I'd be OK with introducing a separator, but I'm also OK with leaving it as is and requiring `select` when you want to do this, because there's no graceful way to support it as-is. (For maximum consistency the real solution is to go back in time and require parens around the multiple values returned from `each` iterators: `(each [(k v) (pairs tbl)] ...)` but honestly now that I look at that I don't like it very much even if it's more consistent.)

**Comment by jaawerth** [comment]
What if we just special-cased `values` here, and use that form as the separator?  It wouldn't make sense for (values ...) to show up anywhere but the end anyway, as it couldn't be used for symbol bindings, so you know it isn't coming from that part of the `[a b c d ...]`.

Along the same lines as requiring `( )` like you say, we make sure that if `(values ...)` is detected in the last position, that's going to provide the iterator. We could make sure to throw an error when `(values ...)` isn't at the end of the vector.

Thoughts?

**Comment by technomancy** [comment]
Yeah, special-casing `values` here is better than introducing some new notation for a separator. It's more discoverable than `select` too.
