### ISSUE TITLE
When to use Fennel vs Janet?

### ISSUE THREAD

**Issue by agentofuser** [bakpakin/Fennel#223]
Sorry for the newbie question. I found Fennel by chance while looking at lua+neovim things and it seems very promising as a nicer way to script nvim.

Then I found out about Janet, and it seems to overlap a lot with Fennel.

Other than "use Fennel if you want access to the Lua ecosystem," are there more reasons why you'd choose one over the other? Thank you in advance.

**Comment by technomancy** [comment]
The main advantage I can see of Janet is that you get immutable data structures out of the box; all the methods for doing so on the Lua runtime are a bit hacky. The other advantage of Janet is it's got built-in tooling to compile to a standalone binary, whereas with Fennel or Lua you need to pull in lua-static. Fennel has a few things that it can't include due to the insistence on zero runtime overhead, like a standard library, so you end up needing Luafun or Lume for that.

Other than the ecosystem questions, Janet has a long way to go before the performance would be competitive with LuaJIT. And Fennel's source is dramatically simpler; around 10x smaller by a LOC comparison, but it's far from an apples-to-apples of course since Janet includes its own runtime. But I haven't looked at it that closely so take my words with a grain of salt.

**Comment by technomancy** [comment]
Hope that answers your question; feel free to reopen if you have any more specific queries.
