### ISSUE TITLE
Bidirectional Lua<->Fennel compilation

### ISSUE THREAD

**Issue by agentofuser** [bakpakin/Fennel#224]
Is there any plan / desire to make it possible to compile Lua syntax to Fennel? I heard that Reason and OCaml are kind of like that (though I don't have first-hand experience), where the programmer can basically choose syntax as an editor setting like highlighting (with the possible exception of some snag around maintaining comments.)

**Comment by technomancy** [comment]
It's not a plan for Fennel to include its own decompiler, since creating a Lua parser is many times more complex than creating a Fennel parser. However, I think we're all in agreement that it would be cool if a decompiler existed as an independent project.

The gotcha is that you would basically be limited to decompiling to the post-macroexpansion version of Fennel in most cases; a decompiler would never be able to reverse arbitrary macros; only some very limited ones (like `when` or `doto` would be easy; `match` would be difficult but probably possible).

If you're interested in tackling this, the Metalua project ships with a working Lua parser in Lua which could be used as a base for this. I'd be happy to offer some guidance.

**Comment by agentofuser** [comment]
Thank you for the pointer to Metalua. Tackling this now would be a bit
above my proficiency level, but I'm glad to know there is interest in it
and I'm grateful for the offer of guidance. Hopefully I'll ramp up first
with smaller contributions :)
