### ISSUE TITLE
Allow entering a file from the REPL

### ISSUE THREAD

**Issue by Benaiah** [bakpakin/Fennel#228]
Racket's REPL has the concept of "entering", where you load a file into the REPL in such a way that the locals in that file are now locals in your REPL. This is very useful for interactive development of functions that you might not want to export from the file but still want to interact with on the REPL. A similar feature in Fennel would make the REPL a lot more useful.

**Comment by jaawerth** [comment]
Love it! In theory this should just require some kind of stack for `env.___replLocals___` and possibly `scope` to easily descend and restore the parent state.

**Comment by technomancy** [comment]
I like this idea.

Do you think "current file" is the right way to frame this rather than
"current module"? They are very closely related, but not exactly the
same thing. The "current module" bit seems more ... conceptually coherent,
but "current file" seems easier to see how it would be implemented.

SLIME has the notion of "comma commands" which are handled directly by
the repl implementation instead of being evaluated as code:

https://common-lisp.net/project/slime/doc/html/Shortcuts.html

That would be a sensible interface to expose this functionality with, I think.

This is a bit tricky because we're constructing new concepts that don't
exist in Lua, but I think within the context of the repl that is
completely appropriate, as long as it doesn't leak outside that.

The design of this should try to make it as clear as possible how our
notion of "current file" or "current module" that we invented is related
to the Lua notion of chunks, which is the building-block we use to build
our thing.

**Comment by technomancy** [comment]
I think this is a good idea, but it should be done as a plugin first, now that plugins can contain repl commands.
