### ISSUE TITLE
Difference between operators and normal functions is confusing

### ISSUE THREAD

**Issue by Kethku** [bakpakin/Fennel#232]
This is likely not a fixable issue, but I just ran into concatenation operator not working with unpack.

``` Fennel
(.. "test" (unpack ["foo", "bar"]))
```

The above code returns "testfoo" ignoring the second argument. This makes sense in lua because the concatenation is an infix operator, but in fennel it doesn't make sense and is very non intuitive.

I'm wondering if there would be a way around this somehow that would lead to less confusion.

(awesome stuff by the way. I'm in progress porting my neovim config to fennel via the Aniseed project. In general the experience has been very satisfying)

**Comment by technomancy** [comment]
Yeah, unfortunately there is no way to do what we would want here,
because expanding `..` to support multiple arities has to be done at
compile time, and the number of return values is typically not statically
knowable. The same problem is present for + and the other arithmetic and
comparison operators.

Of course, we could catch the special case of direct calls to `unpack`,
but a comprehensive solution is impossible since we can't know what
functions return multiple values.

**Comment by Kethku** [comment]
Maybe another option would be to compile in a helper function which gets triggered any time there are more than two operands, or a complicated enough operand? I don't know if there is any precedent for compiling in something like that...

**Comment by technomancy** [comment]
Unfortunately it's not just when there are more than two operands; such a helper function would need to be invoked any time you performed arithmetic on the result of a function call. This would have fairly dire implications for performance.

**Comment by technomancy** [comment]
I think the best we can do is document this as a known gotcha. We mention it already in the docs, but if you can think of a way to make it clearer I'm all ears. Otherwise we can close this out.
