### ISSUE TITLE
Reader macros

### ISSUE THREAD

**Issue by NQNStudios** [bakpakin/Fennel#252]
I've been writing my own Lisp to use for game development, and then I learned about Fennel and it seems like it could be a strong alternative. One feature I need specifically is reader macros, as described [here](https://gist.github.com/chaitanyagupta/9324402). Glancing through the docs it seems like Fennel doesn't have reader macros. Is that right?

**Comment by technomancy** [comment]
I think we can safely say that we will never allow anything-goes reader macros in the style of Common Lisp, because a major goal of Fennel is to have regular, predictable syntax. However, we may at some point introduce custom dispatch that could do some processing on a well-formed Fennel expression using some sort of tagging system; for instance an extension could turn something like #date/2020-05-01T15:00:15 (which is currently a valid symbol) into a parsed representation of a date, or something like that.

Maybe it would help if you could provide some more detail about what you're trying to accomplish.

**Comment by NQNStudios** [comment]
Ah, what I'm doing is definitely out of scope for Fennel then. I want to implement something similar to Inkle's [Ink](https://github.com/inkle/ink/) language as a layer over my Lisp with very different syntax. I'm making decent headway doing it from scratch, so no worries.
