### ISSUE TITLE
Invalid escape sequence when windows paths are in fennel.path when using macros

### ISSUE THREAD

**Issue by reiver-dev** [bakpakin/Fennel#290]
When paths in `fennel.path` table contain backslashes (`\`), they propagate through `searchModule` function. These paths appear in the source file if `doQuote` function is called. The function only wraps the path with quotes, without any additional processing. Backslash in literal string behaves as starting of an escape sequence, which leads to  `invalid escape sequence near ''C:'` error (`filename='C:\abc'`).

Workaround: before compiling change all backward slashes to forward slashes in `fennel.path`.
Possible fix: use `format("%q")` or any other alternative in `doQuote` to sanitize paths.

**Comment by jaawerth** [comment]
@reiver-dev looks like it got merged for the 0.4.1 release (hence why this issue was auto-closed), but I had a go at fixing this in #291 and technomancy tested the backslash parts, but I don't think we've tested it yet on Windows. Hopefully 0.4.1 will Just Work when it comes to `import-macros`/`require-macros` and `include` on Windows, but please feel free to comment back if it gives you any further trouble!
