### ISSUE TITLE
Nested `match` based on guard for a singular value

### ISSUE THREAD

**Issue by The-BigDaddy** [bakpakin/Fennel#321]
The title might be confusing but here's essentially what I'm trying to do:

```
(match fn-arg
  "a" (do-something)
  ;; similar pattern of above repeated a few times
  ([x] ? (and (= (type x) "table") (> (table.maxn x) 1)))
  (each [y x]
    (match y 
      "b" (do-another-thing)
      ; similar pattern as outer match
      )))
```

However putting this inside of a function (with each match just simply printing something) can calling that function with a table returns nothing.

Is there a way to have a guard for a singular value? Is it just a matter of taking the variable in the guard out of the square brackets?

**Comment by technomancy** [comment]
> (match fn-arg ([x] ? (and (= (type x) "table") (> (table.maxn x) 1))) (do-something x))

The guards here are actually unnecessary. If you attempt to match against a table, it will already check that the value is a table before the match can succeed. The `table.maxn` call can be eliminated as well by trying to bind a second value. Viewing the compiled output is instructive here:

> (match fn-arg [x y] (do-something x y))

Compiles to:

> if ((type(fn_arg) == "table") and (nil ~= fn_arg[1]) and (nil ~= fn_arg[2])) then
>   local x = fn_arg[1]
>   local y = fn_arg[2]
>   return do_something(x)
> end

(With the one difference being that it won't work with a table that has gaps in it.)

> However putting this inside of a function (with each match just simply printing something) can calling that function with a table returns nothing.

Yes, that's because `each` returns nil. It sounds like maybe you want to map over the value instead?

> Is there a way to have a guard for a singular value? Is it just a matter of taking the variable in the guard out of the square brackets?

Yes, you can have a guard with any value.

**Comment by The-BigDaddy** [comment]
> If you attempt to match against a table, it will already check that the value is a table before the match can succeed.

Oh, ok. So how would one do a match with a singular type? Because say you normally do a lot of stuff when you generally match a specific string, but you want to do something if the match gets a integer (don't matter what value the integer is)

 ```
(match x
    "x"    (something)
    "a"    (something-else)
    "this" (another-thing)
    int?   (do-thing-with-int) ;; not how I'd assume you'd do it
)
```

What would you do instead of `int?` there? Simple put `int`, or what?

> Yes, that's because each returns nil. It sounds like maybe you want to map over the value instead?

Well I don't want to transform the value in any way, I simply want to call it as the first argument to a function.

**Comment by technomancy** [comment]
> So how would one do a match with a singular type? Because say you normally do a lot of stuff when you generally match a specific string, but you want to do something if the match gets a integer

Oh, I see what you're asking now.

Match patterns without guards can only do equality checks; they can never call arbitrary functions such as `int?`. So to check to see if something is a number, you would always need a guard for that.

```
(match x
  ...
  (i (= :number (type i))) (do-thing-with-int))
```

> Well I don't want to transform the value in any way, I simply want to call it as the first argument to a function. Like print or whatever.

I'm afraid I don't understand the question in that case; maybe you could rephrase it? It looks like in the first example with `each` you are treating a table as an iterator instead of calling `pairs` or `ipairs` on it; maybe that is the problem? If you provide a self-contained example that can actually run instead of just a snippet, it would be easier to understand the problem.

**Comment by The-BigDaddy** [comment]
> It looks like in the first example with each you are treating a table as an iterator instead of calling pairs or ipairs on it; maybe that is the problem?

Ah, you know, that would in fact be the problem haha.

**Comment by technomancy** [comment]
Ah cool; glad you got it figured out.
