### ISSUE TITLE
Is exporting macros in nested table is not possible?

### ISSUE THREAD

**Issue by tami5** [bakpakin/Fennel#335]
Hey everyone, I'm working on creating a new lib with fnl, and I wonder if its true that exporting nested table is not allowed and why is that the case?

The reason I want do such thing is that I want to create wrapper function with same names around my macro function, so that they can also be used in lua files if needed.

Thanks

**Comment by technomancy** [comment]
Unfortunately this is really not very well-explained in the documentation, but there is in fact no way to export macros, because exporting happens at runtime, and macros do not exist at runtime.

You can create a module which is intended to be loaded at compile time with `import-macros`. If you export functions from this module, they will be used as macros by whatever code loads them using `import-macros` but from the perspective of the macro module it's just exporting functions.

**Comment by tami5** [comment]
Thanks @technomancy , I managed to get a workaround for my usecase with metatable, which I'm glad I did as it saved a lot of typing :smile: 

```clojure
(local fs {:exists #(exists $1)
            :dirname #(dirname $1)
            :cwd #(cwd)
            :expand #(expand $1)
            :touch #(touch $1)
            :mkdir #(mkdir $1)
            :ensure #(ensure $1)})


(setmetatable {} { :__index 
                  {:fs fs}})

```

**Comment by technomancy** [comment]
Hm; I don't get it; why not just return `fs`?

**Comment by tami5** [comment]
Ohhh I can do that, didn't realize it was an option. Thanks thats helpful to know
