### ISSUE TITLE
Feature request: get table value by keyword `(:key table)`

### ISSUE THREAD

**Issue by tami5** [bakpakin/Fennel#336]
Hey everyone. 

Not sure if this feature request is possible with lua, but it would be amazing if we can drop the need for `(. table :key)`  to access table values and just use `(:key table)`

Thanks

**Comment by technomancy** [comment]
The particular form of `(. table :key)` as you probably know can simply be shortened to `table.key`. However I assume the question is really about cases where the value of the key is not known at compile time. Because Fennel is a compiler and not a runtime library, cases which are not statically determinable at compile time cannot be changed into key lookup. Even if they could, the performance overhead of doing so would be enough to make this infeasible, I believe.

Also to clarify, "keywords" are really just a more convenient notation for specifying certain kinds of strings; beyond the read-time notation they do not exist as distinct concepts from strings. (Which you probably know, but just in case anyone else reading this doesn't.)
