### ISSUE TITLE
Unable to introduce named locals in macros

### ISSUE THREAD

**Issue by pakeke-constructor** [bakpakin/Fennel#338]
Hi there,
I have been trying to construct a macro that automatically introduces local variables in the form of named function arguments. 
Example:
```clojure
(macro FN_XYZ [expr1 ...]
`(fn [x y z]
    (do
        ,expr1
        ,...)))

(local sum-vector
    (FN_XYZ 
       (+ x y z)))
```
However, I get the error:
`Error: Compile error in file.lua:  macro tried to bind x without gensym.`
However, gensym is not what is needed in my case; instead I want to literally create a named local argument in a function.
(Using `[x# y# z#]` gives another issue, in that it converts to `x` to `_0_`, or something similar,
which means that I cannot access the local as `x` anymore.)

After playing around with it some more, I noticed that `var`, `let` and `local` expressions are also killed in the same manner.

Is this a bug, or is this just the way macros were designed?

If it is an intentional feature, is there any way for named locals to be introduced with macros?
In a language like lua, where global access is often very costly, it seems mad to have macros that don't give the user the ability to automatically localize stuff.

Thank you very much for taking the time to read this length-y issue/question,
I really appreciate the fennel team's dedication to making such an amazing language.

**Comment by technomancy** [comment]
Yeah this is definitely intentional! If we allowed non-gensym here it would be very easy for accidental symbol capture to cause difficult-to-debug problems: https://gist.github.com/nimaai/2f98cc421c9a51930e16#free-symbol-capture This is the most common source of bugs in CL-style `defmacro` systems.

The correct way to write this macro is to allow the caller to provide a name symbol for the local as an argument; that way they can ensure that it will not conflict with an existing local. Something like this:

```
(macro FN_XYZ [args expr1 ...]
 (assert (sequence? args) "expected list of args")
`(fn bindings
    (do
        ,expr1
        ,...)))

(local sum-vector
    (FN_XYZ [x y z]
       (+ x y z)))
```

**Comment by pakeke-constructor** [comment]
Ahhh, okay, that makes a lot of sense.
Thanks a lot for the fast response!
I'll close this now I think, thank you for the insight 👍
