### ISSUE TITLE
Feature request: edn support

### ISSUE THREAD

**Issue by tami5** [bakpakin/Fennel#339]
hey, it would be nice if edn is supported. I'm trying to read an edn file https://clojuredocs-edn.netlify.app/, at first I thought simply removing `,` will make it work. but I endup getting:

```
runtime error: bad argument #1 to 'char' (number expected, got nil)
```

Thanks

**Comment by technomancy** [comment]
The tagged literals function of EDN will never be supported in Fennel,
because it's undesirable to have a situation where two tokens read as a single value.

We are discussing alternate designs at https://todo.sr.ht/~technomancy/fennel/28
but they will not be compatible with EDN because of the above problem.

Do you have a specific example of something other than tagged literals
and commas which is valid EDN but not accepted by the Fennel parser?

**Comment by tami5** [comment]
@technomancy Oh I'm glad there are active development on that important aspect.

No this exactly what I'm having problem with. 

I'm okay with something that partly support edn, and I think its enough for the need of passing data structure between edn-support mediums. With that being said, I wish if the focus be on have edn support. 

Thanks

**Comment by technomancy** [comment]
For full EDN support, there's no reason it can't be done as a 3rd-party library. But it will not be part of Fennel's own parser, because we prioritize different things from EDN.
