### ISSUE TITLE
incorrect result returned from comparing identical symbols.

### ISSUE THREAD

**Issue by jagged-blades** [bakpakin/Fennel#341]
code: 
```
(macro m [p]
  (if (= p 'a)
      1
      2))

(print (m a))
```
When ran in the fennel site's repl, it returns 2, shouldn't it return 1?

**Comment by technomancy** [comment]
In Lua, equality is based on identity. Because these two symbols come from different places, they cannot be identical. For instance, the line number metadata on them must be different. So they are actually two distinct pieces of data that happen to share the same name.

If you want to see whether they have the same name, you need to call `tostring` on each one first, after checking that they are both symbols.
