### ISSUE TITLE
Form-ignoring syntax?

### ISSUE THREAD

**Issue by bbqbaron** [bakpakin/Fennel#348]
Thanks for Fennel - using it with Love2D and it's great. Big fan.

Clojure's `#_` is really handy. Is there some equivalent Fennel option, a form-level comment of sorts? Would that be useful?

**Comment by technomancy** [comment]
We have the `comment` form like Clojure which you can use for multiple
forms. But it does result in a `nil` so it's not always appropriate.

I'm reluctant to add new syntax which is not common across lisps, since
it means implementing it not only in the parser but also in
emacs/vim/etc, as well as pandoc, pygments, and the two different text
editors I maintain written in Fennel!

**Comment by bbqbaron** [comment]
No problem!
