### ISSUE TITLE
Preserve metatables in import-macros

### ISSUE THREAD

**Issue by mrichards42** [bakpakin/Fennel#361]
Discussed a bit over IRC, but this doesn't work:

```clj
;; foo.fnl
(setmetatable {} {:__call (fn [_ x] `(print :hello ,x))})

;; somewhere else
>> (import-macros foo :foo)
>> (foo :world)
Compile error: Compile error in unknown:2
  /usr/local/bin/fennel:2459: upvalue 'macro_2a' is not callable (a table value)

;; the metatable is in macro-loaded, it just isn't attached to foo above
>> ((. (require :fennel) :macro-loaded :foo) :world)
(print "hello" "world")
```

Looks like what's going on is that import-macros creates a new scope, calls `require-macros`, and then copies all the macros that were added to the scope into the new table:
https://github.com/bakpakin/Fennel/blob/ffa3a4b534bf563f4ea55bf2a74118cdb592c489/src/fennel/macros.fnl#L257-L260

I'm not quite sure what the right fix is -- I think what we want is basically `(tset scope.macros (. binding 1) (. macro-loaded modname))`, but I don't think import-macros has access to macro-loaded.

**Comment by technomancy** [comment]
> I'm not quite sure what the right fix is -- I think what we want is
> basically `(tset scope.macros (. binding 1) (. macro-loaded
> modname))`, but I don't think import-macros has access to
> macro-loaded.

Honestly this seems like a good argument for exposing macro-loaded in
the compiler scope. Since it's the macro equivalent of package.loaded it
seems only natural that it should be available.

One other solution would be to use require to access the macro module
table itself. Normally in compiler scope require is replaced with a
version which uses macro-loaded rather than package.loaded. The problem
with this approach is that disabling compiler sandboxing will break it,
because then import-macros would have access to regular runtime require
instead of the macro-loaded-backed one.

**Comment by technomancy** [comment]
I've added `macro-loaded` to compile scope now and used it in `import-macros` so I think this should be fixed.
