### ISSUE TITLE
Interpretation of `\<newline>` is different between Lua and Fennel

### ISSUE THREAD

**Issue by mnacamura** [bakpakin/Fennel#362]
Not sure this is a bug, but I have noticed that `\<newline>` is interpreted differently in Lua and Fennel:
```
Welcome to Fennel 0.9.2 on Lua 5.3!
Use ,help to see available commands.
Try installing readline via luarocks for a better repl experience.
>> (lua "print('\
..hello')")

hello
nil
>> (print "\
..hello")
\nhello
```
In [Lua reference](https://www.lua.org/manual/5.4/manual.html#3.1),

> A backslash followed by a real newline results in a newline in the string.

In Fennel, it results in an escaped newline. Is this behavior intended?

**Comment by technomancy** [comment]
It's definitely intended that the behavior is different in Fennel from
Lua, because Lua has very bad newline behavior by default. Lua needs the
backslash+newline behavior because it fails to handle newlines that lack
backslashes for some reason. Since Fennel does not have that problem,
there should be no reason to escape a newline.

That said, I think the current behavior doesn't have any advantages over
doing what Lua does. If there are compelling reasons to change it, I'd
be open to a discussion around it. But I don't think just doing what Lua
does is a compelling reason on its own, because Lua's behavior is a
workaround for a problem that doesn't exist in Fennel.

**Comment by mnacamura** [comment]
@technomancy Thanks for your reply. I've understand I had misconception that Fennel simply uses Lua's meta characters in string literal.

> But I don't think just doing what Lua does is a compelling reason on its own

Agree. One idea popping up in my mind is to ignore `\<whitespace>*<newline><whitespace>*` like Scheme R6RS+ does. But Lua 5.2+ has `\z`, which does almost the same thing...

**Comment by technomancy** [comment]
Willing to revisit this if there are any compelling arguments, but I figure this is OK to close out now.

**Comment by technomancy** [comment]
After taking a closer look at this situation I think I agree that the current behavior is a bug that only works that way by accident. I think the Lua behavior is better in this case.
