### ISSUE TITLE
Recommended addition to your documentation

### ISSUE THREAD

**Issue by unclefunctor** [bakpakin/Fennel#364]
I've been really getting into this awesome project and I am slowly starting to port my bassh scripts to fennel, because bassh syntax looks like...

  I had a hard time figuring out how to access the command line parameters from a .fnl script.  Eventually through much creative searching I located a piece of code to copy.  Here is a working example:

```
#!/usr/bin/env fennel
(local args [...])
(print "Shall we play a" (. args 1) "?")
```

  The (local args [...]) idiom is not in your docs, so I suggest adding a paragraph for noobs like me.

Thanks :)

**Comment by sogaiu** [comment]
Oh interesting.  I didn't know about `(local args ...)`.

FWIW, I used `arg` for a similar purpose, like this: https://github.com/kanaka/mal/blob/2bbec8ac43e41bff42365fed8d7db86f9b559b45/impls/fennel/stepA_mal.fnl#L301-L303

**Comment by unclefunctor** [comment]
You're right.  "arg" works without the "(local arg)".  I wonder why "(local args ...)" works too? Anyway thanks for the reply :)

**Comment by sogaiu** [comment]
No idea about why `(local args ...)` works as well.

May be @technomancy, @jaawerth, @andreyorst, or others know.

**Comment by technomancy** [comment]
Good catch. I added an explanation of this to `lua-primer.md` in b480bcd since it is not a feature of Fennel but it's still relevant when writing Fennel programs. Do you think it's clear enough?

> I wonder why "(local args ...)" works too?

This is different because it will only bind the first value. If the number of args is known, you can do this instead:

    (local (arg1 arg2 arg3) ...)

But if the number is unknown then putting it in a table is better:

   (local all-args [...])

**Comment by unclefunctor** [comment]
It's fine and you used "command line" so search engines will find it :)
