### ISSUE TITLE
Require lua from macro module

### ISSUE THREAD

**Issue by mrichards42** [bakpakin/Fennel#365]
I have a macro module that basically generates wrappers around a lua module. In 0.9.2 `(require :some-lua-module)` inside a macro module worked fine; on main it breaks with "some-lua-module module not found". Bisecting points the finger at e3de64d9a42e3401363e953eb0bd76c5fdfbe55e, although that might be a red herring -- I added some debug logging before and after and it looks like `safe-require` wasn't being called before that commit, and now it is. It looks like `safe-require` only works on fennel code, so it makes sense that it wouldn't find the lua module.

```clj
;; some-lua-module.lua
print 'hello from lua!'
return {}

;; some-fnl-module.fnl
(print "hello from fennel!")
{}

;; some-macro-module.fnl
(require :some-fnl-module)
(require :some-lua-module)
{}

;; REPL

Welcome to Fennel 0.9.3-dev on Lua 5.4!
Use ,help to see available commands.
>> (require-macros :some-macro-module)
hello from fennel!
Compile error: Compile error in unknown:?
  some-lua-module module not found.


Welcome to Fennel 0.9.2 on Lua 5.4!
Use ,help to see available commands.
>> (require-macros :some-macro-module)
hello from fennel!
hello from lua!
```

**Comment by technomancy** [comment]
The default setup for compiling is to be safe out of the box so that when you need sandboxing it's only required for runtime code. However, the intent is that until 1.0 it should only warn rather than actually block the loading. So today this is a bug, but long-term it's the intended behavior.

What you want to do is disable the compiler sandbox if you want to allow arbitrary code to run at compile time. You can do this with `--no-compiler-sandbox`. But we should also consider accepting a safelist of modules which may be loaded at compile time so you can specify certain ones without disabling the sandbox entirely.

If you'd like to take a shot at implementing the safelist we can talk about the details of how it would work.

**Comment by mrichards42** [comment]
Even with the strict sandbox I still expect that `require` will search for code normally, but load it in the sandbox. So if you try to require a lua module that runs `os.execute("rm /")` that won't run since os isn't in the sandbox, but if that same lua module just defines some functions and returns a table, that's allowed within the sandbox.

**Comment by andreyorst** [comment]
I've noticed this change also. I use this pattern for automated testing:

``` clojure
(macro require-module [module]
  `(local ,(collect [k (pairs (require module))]
             (values k (sym k)))
          (require ,module)))
```

It basically works similarly to `require-macros`, by making all runtime functions available without a namespace part. Using `--no-compiler-sandbox` fixed the issue for me, but I wanted to make it less open, and noticed that only the fact that I'm accessing an `io` table in the required module is causing this error. Using `--allowed-globals io` didn't work for me tho.

**Comment by technomancy** [comment]
@mrichards42 oh, of course; you're right--the error you described is different from what I was saying. Looks like something is screwy with `safe-require`.

**Comment by mrichards42** [comment]
👍 ok, looking a little further I think my issue is b/c safe-require doesn't have a lua-aware loader, and @andreyorst's might be b/c default-macro-searcher only looks at fennel.macro-path?

**Comment by technomancy** [comment]
Yes, it's because of the missing lua macro-loader; you're absolutely right. It's an oversight. Happy to take a patch for this, or I'll get to it later at some point.

It's true that `io` is not in the sandbox, but `print` is included for debugging reasons. We should allow Lua modules to load though, provided they don't use any of the tables excluded from the sandbox.

**Comment by technomancy** [comment]
I think b09dea6 takes care of this; can you see if your code works now?

**Comment by mrichards42** [comment]
Yep, that did it thanks @technomancy!

The only remaining oddity is that `require` in macros searches fennel.macro-path instead of fennel.path, so if you want to require an ordinary fennel module you have to make sure those two paths are kept in sync . . . although I can't come up with a reason you'd ever want those paths to diverge (aside from init-macros) so you probably need to do that anyways.
