### ISSUE TITLE
Fennel in embedded systems

### ISSUE THREAD

**Issue by sherief** [bakpakin/Fennel#375]
I have some use cases where lisp-on-lua would make for an excellent interface - some of which are on embedded systems with very limited resources. Lua, out of the box, can adapt very well to these environments: I create a new state and I only load the exact subset of libraries I want, so for example I skip the `io` package on ARM Cortex M0 platforms, and just add a simple `print()` that maps to UART. 

I would love to use Fennel on these parts, but the current version seems tightly coupled and a bit too big (I wouldn't dare say monolithic in this case :D) for the platforms. I tried doing some work towards this, and for example replaces things like:
`package.preload["fennel.utils"] = package.preload["fennel.utils"] or function(...)`
with
`fennel.utils = function(...)`
to avoid needing `require()` - but eventually I hit a wall. The compiler and parser rely on `friend` and that calls some functions from `io` and it gets complicated from there.

Would it be possible to refactor Fennel to support this use case? I'd like to have enough of the parser / compiler running on the Cortex M0 platform so that I can call `fennel.eval()` or `fennel.compileStr()` on a Lua state with very little else loaded. 

A parser / compiler module that relies only on `string` and `table` would be perfect. Would this be feasible? And most importantly, is the embedded use case important enough to the maintainers to warrant this? I would love to have IOT devices and other uCs that I can command via lisp while reusing the investment of Lua bindings that already exist.

Thanks for developing Fennel!

**Comment by technomancy** [comment]
> I have some use cases where lisp-on-lua would make for an excellent
> interface - some of which are on embedded systems with very limited
> resources.

Cool. I got an early version of Fennel running in 80kb on an ESP8266 but
I had to rip the entire macro system out. It was running on eLua which
is a fork of PUC 5.1, so it was pretty limited. How much ram are you
talking about in your case?

> I tried doing some work towards this, and for example replaces things like:
> `package.preload["fennel.utils"] = package.preload["fennel.utils"] or function(...)`
> with
> `fennel.utils = function(...)`
> to avoid needing `require()` - but eventually I hit a wall.

Can you be more specific? What about require is causing trouble?

It's unlikely we could decouple from require altogether, because it's
the cornerstone of our self-hosting strategy to use require-as-include.

It should be possible to write a shim replacement for require which
only checks package.loaded and falls back to package.preload if it's not
found, ignoring searchers.

> The compiler and parser rely on `friend` and that calls some functions
> from `io` and it gets complicated from there.

There are many uses of io fields; only one of them comes from the
fennel.friend module. This one is disabled by using {unfriendly=true} in
your options table when invoking the compiler. One thing I noticed is
that most of the other references to io check to see whether it exists
before proceeding.

I've made a change in 31c3eff which automatically disables the
fennel.friend module when it notices that the io table is not
present. Perhaps that will get you what you need?

> A parser / compiler module that relies only on `string` and `table`
> would be perfect. Would this be feasible? And most importantly, is the
> embedded use case important enough to the maintainers to warrant this?

I think limiting it to just string and table is too extreme. We need
require, package, and math too. But with the change mentioned above,
this snippet works:

```lua
for k,v in pairs(_G) do
   if(k~= "table" and k~= "string" and
         k~= "math" and k~= "package" and
         k~= "_G" and type(v) == "table") then
      _G[k] = nil
   end
end

local fennel = require("fennel")

fennel.eval("(print (+ 3 32))")
```

How's that look to you?

**Comment by technomancy** [comment]
I have a branch here where I've added the ability to skip certain
modules from being included. I've used it on the compiler to generate
"minifennel.lua" in the makefile:

  https://git.sr.ht/~technomancy/fennel/commit/skip-include

Right now I have fennel.lua clocking in at 172kb and minifennel.lua at
138kb. Not tiny, but it should be a big improvement!

**Comment by sherief** [comment]
Thank you! That's perfect, I managed to squeeze it in finally! I'll see how I can cut down its memory footprint in an acceptable manner and contribute any changes I come up with. 

Again, thank you so much - for the timely response and for the helpful contributions.

**Comment by technomancy** [comment]
Please let us know how it turns out, either here or on the mailing list
or in chat. I'm curious to see what you do with it!
