### ISSUE TITLE
Fennel binary for Windows fails to run, does not have `liblua.a` linked statically

### ISSUE THREAD

**Issue by cpkio** [bakpakin/Fennel#417]
The title says it all.

**Comment by cpkio** [comment]
@technomancy File naming should not affect linker's ability to find function signatures in a linked file IMO, but I really don't know the compiler's intrinsic details. Recompile and post the executable somewhere.

BTW are you sure the compiler should be `i686*`, not `x86_64*`?

**Comment by technomancy** [comment]
OK, I think I've traced this down to a change I made trying to cross-compile everything from arm64. The working build can only be done on linux x86_64 instead of being portable, but it seems to have the advantage of actually working, so there's that.

Here's a test build: https://p.hagelb.org/fennelexe-test

Fixed in 4a82a35
