### ISSUE TITLE
Some general questions invoked by a stack trace

### ISSUE THREAD

**Issue by noncom** [bakpakin/Fennel#489]
I'm doing this:

```fennel
(local fennel (require :fennel))
(local view (require :fennel.view))
(local parser (require :fennel.parser))

(tset debug :traceback (. fennel :traceback)))

(fn ast [s]
  (let [(f1 f2) (parse s)]
  res))

(fn m [o]
  (let [res (getmetatable o)]
    (print (.. "(m): _" (type o) "_ " (view o) "  => " (view res)))
    res))

(fn pm [mt]
  (print "fv=" (rawget mt :__fennelview))
  (print "ts=" (rawget mt :__tostring)) 
  (print "fv=" ((rawget mt :__fennelview)))
  (print "ts=" ((rawget mt :__tostring))))

(fn test-01 []
  (-> "(fn [a] a)" ast m pm))

(test-01)
```

And getting this:

```fennel
>> (m): _table_ (fn [a] a)  => {1 "LIST"
   :__fennelview #<function: 0x58a63da439f0>
   :__tostring #<function: 0x58a63da439f0>}
fv= function: 0x58a63da439f0
ts= function: 0x58a63da439f0
runtime error: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
  [C]: in function 'for iterator'
  /home/noncom/work/Fennel/fennel:5620: in function 'maxn'
  /home/noncom/work/Fennel/fennel:5669: in function ?
  [string "local f10 = ___replLocals___["f1"] local f20 ..."]:5: in function ?
  /home/noncom/work/Fennel/fennel:897: in function ?
  [C]: in function 'xpcall'
  /home/noncom/work/Fennel/fennel:902: in function ?
  /home/noncom/work/Fennel/fennel:929: in function ?
  /home/noncom/work/Fennel/fennel:939: in function ?
  [C]: in ?  
```

In my understanding `function: 0x58a63da439f0` should just print what `fennel.view` would have printed. But calling it causes the error. Which causes quite some questions from my side.

What would be the idiomatic way to deal with such stack trace? The problems I have with this, and questions are:
- Why is this an error at all? What did I do wrong? It seems like I simply called functions that the API itself provided.
- Almost all function names in the trace are "?" and the trace is from the generated Lua code of Fennel, not the Fennel code of Fennel. My best guess is that it's because the source maps are not available in the compiled version of Fennel, but.. is there any way to include them then? This state seems useless, the overhead of including them seems to be minimal, but it would help with errors coming from inside Fennel?
- Not sure what is the `"local f10 = ..."` string, is it the generated function for printing the AST back into the string, and so is a closure that has no location? If it's not a closure then is there an easy way to map it back to the Fennel code? I did install `fennel.traceback`, but it didn't seem to help.
- Is there an easy way to enable full non-abbreviated printout of such generated functions? At least maybe seeing it awhole would give an idea of what is it, even if it's a closure.
- How do you generally deal with such errors in Fennel? There might be an idiomatic way that I'm not aware of.

My aim with this code is to inspect the AST generation of Fennel, so I'm just pocking the API, and throwing various strings at it.
I would be very grateful for some insights on these points!

Disclaimer: I might be missing some obvious stuff here, but from my reading of the docs I haven't really yet found definite answers to these questions.

**Comment by technomancy** [comment]
I think there might have been a mistake pasting; that code as given above doesn't compile.

Anyway, the `fennel.parser` function gives you a parser function: https://fennel-lang.org/api#convert-text-into-ast-nodes That is to say, given a string, it returns a function which when called will return successive values of a success boolean and a parsed AST. There is no assumption that the string being parsed contains only one form, but if you only want one form, you can call it just one time. So it would be something like this:

```fennel
(local {: view : parser : traceback} (require :fennel))

(set debug.traceback traceback)

(fn pm [mt]
  (print :pm mt)
  (print "fv=" (rawget mt :__fennelview))
  (print "ts=" (rawget mt :__tostring))
  (print "fv=" ((rawget mt :__fennelview)))
  (print "ts=" ((rawget mt :__tostring))))

(fn test-01 []
  (let [code "(fn [a] a)"
        parse (parser code)
        (ok? parsed) (parse)
        mt (getmetatable parsed)]
    (print (.. "(m): _" (type mt) "_ " (view mt) "  => " (view mt)))
    (pm mt)))

(test-01)
```

This fails because the fennelview metamethod needs an argument, and it's being called without one: `((rawget mt :__fennelview) ast)`

The metatable alone is not enough for the `pm` function; it needs the original AST as well:

```fennel
(fn pm [mt ast]
  (print :pm mt)
  (print "fv=" (rawget mt :__fennelview))
  (print "ts=" (rawget mt :__tostring))
  (print "fv=" ((rawget mt :__fennelview) ast))
  (print "ts=" ((rawget mt :__tostring) ast)))
```

Once you make that change, it works fine:

```
(m): _table_ {1 "LIST"
 :__fennelview #<function: 0x558d3f47ee50>
 :__tostring #<function: 0x558d3f47ee50>}  => {1 "LIST"
 :__fennelview #<function: 0x558d3f47ee50>
 :__tostring #<function: 0x558d3f47ee50>}
pm	table: 0x558d3f47f050
fv=	function: 0x558d3f47ee50
ts=	function: 0x558d3f47ee50
fv=	(fn [a] a)
ts=	(fn [a] a)
```

But anyway, that is really just an overly complicated way to call `(tostring ast)`.

**Comment by technomancy** [comment]
To address the individual questions:

> Why is this an error at all? What did I do wrong? It seems like I simply called functions that the API itself provided.

As above, `fennel.parser` returns an iterator, not the parsed values. But also the `__fennelview` method needs to be passed an argument of what it is you want to view. The public `fennel.view` function itself will give sensible output when passed a nil value, but the private individual data-type specific submethods will not.

> Almost all function names in the trace are "?" and the trace is from the generated Lua code of Fennel, not the Fennel code of Fennel. My best guess is that it's because the source maps are not available in the compiled version of Fennel, but.. is there any way to include them then? This state seems useless, the overhead of including them seems to be minimal, but it would help with errors coming from inside Fennel?

We don't currently have any way to dump source maps. Even if we did, I don't think we would do it for the compiler itself, because getting a stack trace of the compiler is pretty rare; you have to go far out of your way to trigger it. You can't trigger it using the public API (calling `tostring` or `fennel.view` on an AST node).

> Not sure what is the "local f10 = ..." string, is it the generated function for printing the AST back into the string, and so is a closure that has no location? If it's not a closure then is there an easy way to map it back to the Fennel code? I did install fennel.traceback, but it didn't seem to help.

This is a quirk of the REPL; when you're running code that didn't come from a file, Lua uses the source of the chunk being evaluated. (Functions that come from a file won't have this problem.) It might be possible to override this, or at least give a more helpful indicator here. Will have to think about it.

> How do you generally deal with such errors in Fennel? There might be an idiomatic way that I'm not aware of.

Almost all errors you make with the compiler will give you compile errors which show the exact line number highlighted:
![compile-error](https://github.com/user-attachments/assets/d36b4f30-1579-44aa-bd66-438b88e4b48c) But in general taking internal functions that aren't part of the public API and calling them with the wrong number of arguments will be confusing no matter what; I don't think there is a way around that.

**Comment by noncom** [comment]
> I think there might have been a mistake pasting; that code as given above doesn't compile.

Ah sorry, was copying and cutting from Emacs on the other end of SSH. Corrected.

> ... the explanation of everything else ...

Got it! The main fallacy was that I totally missed that the functions might have been expecting args 😄. Too much C# and Java sometimes make me forget that type/signature errors don't exist in Lua and other dynamic languages, resulting in all kinds of runtime errors instead. I really do habitually expect to be able to call anything, and get a detailed explanation of errors if they happen. And this approach doesn't work well for dynamic languages.

I specifically tried to not look into the source of the parser up to now, but yeah that doesn't work well. Also gotta read the Fennel Lua API document.

Would've been great if Lua could present some more metadata about functions, like maybe the number of args or arg names, at least in some debug mode.

> This is a quirk of the REPL; when you're running code that didn't come from a file, Lua uses the source of the chunk being evaluated. (Functions that come from a file won't have this problem.) It might be possible to override this, or at least give a more helpful indicator here. Will have to think about it.

I see, right. I wonder if any good solution is possible, and what would it be.

Imho the ability to load random unattributed chunks is technically cool, but is a dent in traceability. A long time ago I was faking it in a similar situation by making Lua think that it was loading actual modules with generated names instead of just evaluating a chunk. So I was also actually storing the text of these generated modules in a kind of "virtual filesystem", so that the whole REPL/network/database-sourced input was being preserved, and could be examined/changed if needed. But I was relying on the host Java application a lot for almost all of the additional logic, and it was relatively heavy.

As all the questions have been well addressed, I'm closing this issue!
Thank you very much for the insights!
