### ISSUE TITLE
Improve cosmetics of compilation output

### ISSUE THREAD

**Issue by technomancy** [bakpakin/Fennel#53]
A few things that would be nicer:

* [x] Fixing a bug with side-effects in 9acf9cda88be5e1071b2d1639d016a7651fbbf8b caused spurious `do _ = nil end` lines to be emitted in compilation output.
* [ ] Functions are always compiled and set to gensym'd locals; this is a bit untidy when they could be emitted directly as expressions.
* [x] Can we detect cases where mangling dashes to `_2d` is unnecessary? If dashes could mangle to underscores when there's no conflict then the code emitted would be a fair bit more readable.

**Comment by bb010g** [comment]
Regarding mangling dashes, I'd actually be up for doing a Nim-style mangling where dashes are always converted into underscores. We can't tell if an arbitrary table `t` has a key `a_b` without testing every time anyways, and would make dealing with Lua libraries that use snake case consistently much nicer.

**Comment by Benaiah** [comment]
@bb010g that seems really confusing to me, considering that you can use underscores literally in Fennel already. `(let [a-b 1 a_b 2] a-b)` should _not_ return 2 IMO. Additionally, that approach doesn't do anything for CamelCase, which in my (limited) experience is more common than snake_case.

The biggest issue with dash-mangling that I see is that we have no way of knowing what's in the global table at runtime, so there's no way to detect conflicts with those names.

**Comment by bakpakin** [comment]
Yes, there are some issues. Namely, if you create a global `my-global`, it can be accessed with `my_global`, which is a bit strange.

@Benaiah your example will work fine regardless. The current name mangler treats local variables a bit differently than globals, and will automatically change the mangling to be unique for every local variable.

**Comment by bb010g** [comment]
@Benaiah Yeah. The biggest issue is that you'd break existing code that used both dashes and underscores like that right now, but pre-1.0 Fennel is the best time to do stuff like that. And you're right about it not doing anything for CamelCase, but that's because we can't control Lua's semantics, unlike Nim. I just can't think of many cases where you'd actually want to have both `a-b` and `a_b` as variables, and this is a case where we can improve readability without running into Lua constraints. If we make it clear that dashes in symbols are really underscores, I don't think there would be any problems with it after the first time someone runs into it.

It would be interesting though to see if you could use a macro with `eval-compiler` to change the mangler and swap a portion of code over to mangling snake-case as camelCase, which you could then disable when done.

**Comment by Benaiah** [comment]
@bakpakin @bb010g Good point on my `let` example, and I do think that this only affecting globals is definitely an improvement over the alternative. I am 100% ok with breaking existing code, so that's not my concern. Global collisions still worry me, but since locals override them it shouldn't be an issue very often (also, you can create a global named `dash_2dname` and have the same collision issue now). Another concern I had was that this makes table keys operate differently than variable names - i.e., `{:dash-name 1}` would compile to `{ "dash-name" = 1 }`, while `(local dash-name 1)` would compile to `local dash_name = 1`. This seems a little weird to me, but the two are already distinct (`:word` literals are never mangled). However, this does seem to make key/value table destructuring (which is admittedly an unimplemented feature) pretty weird - how would we handle `(let [{ dash-name } {:dash-name 1}] dash-name)`? It's possible that name mangling precludes straightforward string-key destructuring entirely, but I'm curious what your thoughts on this are.

I'm definitely not dead set against the idea, just to be clear. It's definitely a big improvement to output readability. I just want to make sure we've considered the edge case of rewriting symbol names for any purpose other than disambiguation.

**Comment by bb010g** [comment]
If we always do the dash conversion, then `(let [{ dash-name } {:dash-name 1}] dash-name)` just becomes something like `local dash_name = ({ dash_name = 1 }).dash_name ...` and stays consistent.

**Comment by Benaiah** [comment]
@bb010g are you suggesting that we mangle `:word-literals` completely, or _just_ replace their dashes with underscores? If we just replace, we would still have to do something like my first edit to handle cases like `(let [{dash-slash/name} {:dash-slash/name 1}] dash-slash/name)`, since `dash-slash/name` would be compiled to `dash_slash_2fname` while `:dash-slash/name` would be compiled to "dash_slash/name". If we mangle them the same way as actual AST symbols (e.g., variable names), then we run into the issue that you can't retrieve string keys that use the unmangled forms (e.g., you couldn't retrieve the value from a lua table like `{ "slash/name = 1 }` with the fennel code `(. tbl :slash/name)`. That's an acceptable tradeoff to me, and fully-mangling `:word`s prevents us having to special-case destructuring _and_ prevents the `env` issue (if you set `env` using `:word` literals, they're automatically mangled correctly), so I think that would be the approach I'd be most comfortable with.

**Comment by bakpakin** [comment]
I’m very against any sort of mangling in keywords. Symbols are not keywords, there really isn’t supposed to be any direct correlation at all. The only correlation should be is multi syms, in which the leading part is mangled, and the trailing parts are taken as literals.

I’m on my phone right now, but I thought destructuring tables required having both the key and binding separately.

**Comment by Benaiah** [comment]
@bakpakin ok - I'm not a huge fan of mangling keywords either, it just seemed like a better option than partially-mangling them (e.g., just replacing dashes). If we limit destructuring syntax to explicit pairs (`(let [{dash-name :dash-name} {:dash-name "value"}] dash-name)` it avoids the issue entirely. That's a slightly more verbose named-destructuring syntax than most languages, but I think the simplicity and symbol/keyword decoupling it brings is worth it.

**Comment by bb010g** [comment]
Oh yeah, sorry. Didn't think about how we handle keys fully. That would cause issues destructing keys with dashes if we didn't use explicit keys. I am also against mangling keywords. :)

That does cause `a.b-c` to translate to `(. a :b_c)`, but doing explicit accesses of string keys are uncommon, and again, I'd have to wonder how much of a problem people would have with this after they encounter it the first time and learn what Fennel does.

**Comment by Benaiah** [comment]
@bb010g At this point there's enough edge cases and gotchas involved that I'd prefer not to convert dashes to underscores at all, but if that's what we decide to do then I think `a.b-c` translating to `(. a :b_c)` is fine - as a user, I'd expect the other components in the dotted path to behave the same as the first.

Note that this convention (translating dashes in non-`:`-prefixed keys to underscores) would have to be manually enforced by other macros if I'm understanding correctly.

**Comment by bb010g** [comment]
Yeah. That would be annoying for macro writers. We _could_ solve that by exposing the mangler to macros, but this is getting to be a lot of edge cases.

**Comment by technomancy** [comment]
All the concerns in the initial issue have been addressed except this:

> Functions are always compiled and set to gensym'd locals; this is a bit untidy when they could be emitted directly as expressions.

And I remember there was a really good reason for this, tho I can't recall exactly what it is off the top of my head. In any case if you provide an "internal name" to all your `fn`s then it's not an issue. And I think we decided against mangling, so I think this can be closed on out.
